image: node:11

services: 
   - postgres

before_script:
  - npm install
  - npx lerna bootstrap

cache:
  paths:
    - node_modules/
    - server/node_modules/
    - client/node_modules/


variables:
  POSTGRES_DB: js-study
  POSTGRES_USER: js
  POSTGRES_PASSWORD: 123

stages:
  - prepare
  - build
  - test
  - deploy

prepare:
  stage: prepare
  script:
    - node --version

test-server:
  stage: test
  variables:
    TEST_DATABASE_URL: "postgresql://js:123@postgres:5432/js-study"
  script:
    - cd server
    - npm run test:ci

test-client:
  stage: test
  script:
    - cd client
    - npm run test

dev-deploy:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=node-heroku-dpl --api-key=$HEROKU_API_KEY
    - echo "Deployed to dev server"
  only:
    - develop